version: "3.9"
services:
  elwood:
    container_name: elwood-container
    build: ./
    volumes:
      - $PWD:/elwood
  dev-elwood:
    container_name: dev-elwood
    build: .
    volumes:
      - $PWD:/elwood
    command: tail -F anything
    profiles: ["dev"]
