name: Python Test

on:
  push:
    branches:
      - main  # Change to your main branch name
  pull_request:
    branches:
      - main  # Change to your main branch name

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change to your desired Python version

      - name: Install GDAL dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa -y
          sudo apt-get update -q
          sudo apt-get install -y libgdal-dev gdal-bin libspatialindex-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.33.6
          pip install setuptools<58
          pip install numpy==1.22
          pip install coverage pytest
          pip install --global-option="build_ext" --global-option="-I/usr/include/gdal" gdal==$(gdal-config --version) -r requirements.txt

      - name: Run pytest
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
